### ISSUE TITLE
Splitting into Redux/React packages

### ISSUE THREAD

**Issue by maartenbusstra** [apollostack/apollo-react#2]
Do you think it might be a good idea to split these into 2 separate packages? Like `apollo-react` and `apollo-redux`?

**Comment by stubailo** [comment]
No, because the redux part is a very small component. Apollo client uses redux internally so the integration is not complicated. Plus, redux seems to be the state management of choice for many react devs.

**Comment by maartenbusstra** [comment]
Hmm, alright. Packages being small didn't stop Dan from publishing redux-thunk separately, though. And let's not forget about left-pad. ;)

Anyways, it looks very slick! Props to you guys.

**Comment by stubailo** [comment]
Yeah, I guess my hope is that if you're starting a new React project, you can just use `react-apollo` and not worry about whether you need to connect GraphQL data or Apollo data.

If we did have a small package for redux integration, how would it be different? It would just support more options for `connect` or something?

**Comment by maartenbusstra** [comment]
To be honest, I think `connect` should be in the `apollo-react` package, since it's being used to "connect" to React, just like `<Provider />`.

The `apollo-redux` package could include helper functions to get the reducer and the middleware for a Redux store. Something like;
```
import { createStore, combineReducers, applyMiddleware } from 'redux';
import { ApolloClient } from 'apollo-client';
import { Provider } from 'apollo-react';
import { createReducer, createMiddleware } from 'apollo-redux';

import { todoReducer, userReducer } from './reducers';

const client = new ApolloClient();

const store = createStore(
  combineReducers({
    todos: todoReducer,
    users: userReducer,
    apollo: createReducer(client),
  }),
  applyMiddleware(createMiddleware(client))
);

ReactDOM.render(
  <Provider store={store} client={client}>
    <MyRootComponent />
  </Provider>,
  rootEl
)
```

**Comment by stubailo** [comment]
Right, but here's the thing - `apollo-client` uses `createReducer` internally, so it would just be a vanity package. But yeah, let's keep it one package for now and then if there is a good reason we can split it up. Going to close this issue if that's OK!
